# Generated by Django 6.0.2 on 2026-03-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineUserConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=255, unique=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="onlineuserconnection",
            index=models.Index(fields=["last_seen"], name="forum_online_last_se_775495_idx"),
        ),
        migrations.AddIndex(
            model_name="onlineuserconnection",
            index=models.Index(fields=["user", "last_seen"], name="forum_online_user_id_30253d_idx"),
        ),
    ]
