# Generated by Django 6.0.2 on 2026-03-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_onlineuserconnection"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="onlineuserconnection",
            new_name="forum_onlin_last_se_746980_idx",
            old_name="forum_online_last_se_775495_idx",
        ),
        migrations.RenameIndex(
            model_name="onlineuserconnection",
            new_name="forum_onlin_user_id_becbd7_idx",
            old_name="forum_online_user_id_30253d_idx",
        ),
    ]
