# Generated by Codex on 2026-04-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0003_rename_forum_online_last_se_775495_idx_forum_onlin_last_se_746980_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncOperation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("email_staff", "Email staff users"),
                            ("email_non_staff", "Email non-staff users"),
                            ("forum_long_op", "Forum long OP"),
                        ],
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("result", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="async_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-created_at"],
            },
        ),
    ]
